services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: hotcrm
      POSTGRES_PASSWORD: hotcrm
      POSTGRES_DB: hotcrm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
